name: build docker images

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - master

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            mileszim/whisper-ui:latest
            mileszim/whisper-ui:cpu
            ghcr.io/mileszim/whisper-ui:latest
            ghcr.io/mileszim/whisper-ui:cpu
          cache-from: type=registry,ref=mileszim/whisper-ui:latest
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.gpu
          push: true
          tags: |
            mileszim/whisper-ui:gpu
            ghcr.io/mileszim/whisper-ui:gpu
          cache-from: type=registry,ref=mileszim/whisper-ui:gpu
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
